### ISSUE TITLE
scrollTop and scrollLeft should be clearer about their sign

### ISSUE THREAD

**Issue by dbaron** [WICG/ViewportAPI#29]
The [definition](https://rawgit.com/WICG/ViewportAPI/master/index.html#the-visualviewport-interface) of <code>scrollTop</code> and <code>scrollLeft</code> could be interpreted as requiring a negative sign in the normal case, although probably not, given that it says "distance" rather than "location" or "offset", since it's described as _from_ the visual viewport _to_ the layout viewport (rather than the other way around).

However, I'm not 100% sure that we can promise that it always _should_ be a nonnegative number, e.g., with touch overscrolling.

This makes me think that it should be described as an offset or location, but with the "from" and the "to" swapped from the way they currently are.

Noticed while reviewing the spec for https://github.com/w3ctag/spec-reviews/issues/128 .

**Comment by ymalik** [comment]
In Chrome's viewport architecture, the visual viewport is always contained within the layout viewport, which is why scrollTop and scrollLeft will always be non-negative (I believe even with touch overscrolling). Though, this may not be the case for other vendors, so I agree that we should avoid using "distance" and use position or offset with the "from" and "to" swapped. Thanks for bringing this up!
